/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MapRouteImport } from './routes/map'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PracticeProfileRouteImport } from './routes/practice-profile'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SendRouteImport } from './routes/send'
import { Route as AccountantsIdRouteImport } from './routes/accountants.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeProfileRoute = PracticeProfileRouteImport.update({
  id: '/practice-profile',
  path: '/practice-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantsIdRoute = AccountantsIdRouteImport.update({
  id: '/accountants/$id',
  path: '/accountants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/inbox': typeof InboxRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/practice-profile': typeof PracticeProfileRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/accountants/$id': typeof AccountantsIdRoute
  '/book/$id': typeof BookIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/inbox': typeof InboxRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/practice-profile': typeof PracticeProfileRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/accountants/$id': typeof AccountantsIdRoute
  '/book/$id': typeof BookIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents': typeof DocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/inbox': typeof InboxRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/practice-profile': typeof PracticeProfileRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/accountants/$id': typeof AccountantsIdRoute
  '/book/$id': typeof BookIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/chat'
    | '/clients'
    | '/inbox'
    | '/map'
    | '/practice'
    | '/practice-profile'
    | '/profile'
    | '/scan'
    | '/send'
    | '/accountants/$id'
    | '/book/$id'
    | '/documents/$id'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/chat'
    | '/clients'
    | '/inbox'
    | '/map'
    | '/practice'
    | '/practice-profile'
    | '/profile'
    | '/scan'
    | '/send'
    | '/accountants/$id'
    | '/book/$id'
    | '/documents/$id'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/chat'
    | '/clients'
    | '/inbox'
    | '/map'
    | '/practice'
    | '/practice-profile'
    | '/profile'
    | '/scan'
    | '/send'
    | '/accountants/$id'
    | '/book/$id'
    | '/documents/$id'
    | '/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRoute
  InboxRoute: typeof InboxRoute
  MapRoute: typeof MapRoute
  PracticeRoute: typeof PracticeRoute
  PracticeProfileRoute: typeof PracticeProfileRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  AccountantsIdRoute: typeof AccountantsIdRoute
  BookIdRoute: typeof BookIdRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-profile': {
      id: '/practice-profile'
      path: '/practice-profile'
      fullPath: '/practice-profile'
      preLoaderRoute: typeof PracticeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountants/$id': {
      id: '/accountants/$id'
      path: '/accountants/$id'
      fullPath: '/accountants/$id'
      preLoaderRoute: typeof AccountantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRoute,
  InboxRoute: InboxRoute,
  MapRoute: MapRoute,
  PracticeRoute: PracticeRoute,
  PracticeProfileRoute: PracticeProfileRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  AccountantsIdRoute: AccountantsIdRoute,
  BookIdRoute: BookIdRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
